version: "3"
services:
  node:
    build: 
      context: .
      dockerfile: node.dockerfile
    volumes:
      - ./web:/home/node/app
    ports: 
      - "8080:8080"
    command: /bin/sh -c "while sleep 1000; do :; done"

    
    adminer:
        image: adminer
        ports: 
            - 8088:8080